// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Models;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(WebContext))]
    partial class WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.TblUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("displayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblUsers");
                });

            modelBuilder.Entity("webapi.Models.TbllShoppingList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("displaynamereceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("displaynamesender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idreceiver")
                        .HasColumnType("int");

                    b.Property<string>("locate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userreceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usersender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TbllShoppingList");
                });

            modelBuilder.Entity("webapi.Models.TbllistFood", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("displaynamereceiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senderdisplayname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sendernumberphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userreceiver")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TbllistFood");
                });
#pragma warning restore 612, 618
        }
    }
}
